server:
  port: 8081

spring:
  application:
    name: cloud-base

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false