server:
  port: 8082

spring:
  application:
    name: cloud-base

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  #灰度标识
  instance:
    metadata-map:
      version: V2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
